/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    {
      type: 'category',
      label: '00 · Handbook Introduction',
      collapsed: false,
      link: {
        type: 'doc',
        id: '00-handbook-introduction/what-is-genai-llm',
      },
      items: [
        {type: 'doc', id: '00-handbook-introduction/what-is-genai-llm', label: 'What It Is'},
        {type: 'doc', id: '00-handbook-introduction/who-this-is-for', label: 'Who This Is For'},
        {type: 'doc', id: '00-handbook-introduction/scope-and-applicability', label: 'Scope and Applicability'},
        {type: 'doc', id: '00-handbook-introduction/prerequisites-and-entry-criteria', label: 'Prerequisites'},
        {type: 'doc', id: '00-handbook-introduction/how-to-use-this-repo', label: 'How to Use This Repository'},
        {type: 'doc', id: '00-handbook-introduction/genai-llm-map', label: 'Handbook Map'},
        {type: 'doc', id: '00-handbook-introduction/standard-core', label: 'Standard Core'},
        {type: 'doc', id: '00-handbook-introduction/style-guide', label: 'Style Guide'},
        {type: 'doc', id: '00-handbook-introduction/glossary', label: 'Glossary'},
      ],
    },
    {
      type: 'category',
      label: '01 · Handbook Method',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Overview & Loop',
          items: [
            '01-handbook-method/01-overview',
            '01-handbook-method/02-ideation-and-use-case',
            '01-handbook-method/03-model-selection',
            '01-handbook-method/cost-intuition',
            '01-handbook-method/cheat-sheet',
            '01-handbook-method/discovery-brief',
            '01-handbook-method/the-genai-llm-loop',
            '01-handbook-method/genai-llm-loop-spec',
            '01-handbook-method/working-agreements-for-teams',
          ],
        },
        {
          type: 'category',
          label: 'Artifacts & Delegation',
          items: [
            '01-handbook-method/intent-spec',
            '01-handbook-method/constraint-spec',
            '01-handbook-method/delegation-contract',
            '01-handbook-method/generation-requests',
            '01-handbook-method/review-and-interrogation',
            '01-handbook-method/acceptance-criteria',
            '01-handbook-method/iteration-and-release',
            '01-handbook-method/artifact-contracts',
            '01-handbook-method/accountability-and-delegation',
            '01-handbook-method/risks-production-challenges',
          ],
        },
        {
          type: 'category',
          label: 'Techniques & Tools',
          items: [
            '01-handbook-method/prompt-engineering',
            '01-handbook-method/05-rag',
            '01-handbook-method/instruction-tuning',
            '01-handbook-method/fine-tuning',
            '01-handbook-method/peft',
            '01-handbook-method/07-tool-use-and-agents',
            '01-handbook-method/testing-tools',
            '01-handbook-method/evaluation',
          ],
        },
        {
          type: 'category',
          label: 'Core Skills',
          items: [{type: 'autogenerated', dirName: '01-handbook-method/core-skills'}],
        },
        {
          type: 'category',
          label: 'Evaluation Library',
          items: [{type: 'autogenerated', dirName: '01-handbook-method/08-evaluation'}],
        },
      ],
    },
    {
      type: 'category',
      label: '02 · Execution Patterns',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '02-execution-patterns'}],
    },
    {
      type: 'category',
      label: '03 · Professional Scenarios',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '03-professional-scenarios'}],
    },
    {
      type: 'category',
      label: '04 · Tooling & Frameworks',
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: '04-tooling-and-frameworks/00-tooling-index',
          label: 'Overview',
        },
        {
          type: 'category',
          label: 'Tooling',
          items: [
            '04-tooling-and-frameworks/01-ide-setup-cursor',
            '04-tooling-and-frameworks/02-cli-agents',
            {type: 'autogenerated', dirName: '04-tooling-and-frameworks/01-cli-copilots'},
          ],
        },
        {
          type: 'category',
          label: 'Frameworks',
          items: [
            {type: 'autogenerated', dirName: '04-tooling-and-frameworks/02-llm-frameworks'},
          ],
        },
        {
          type: 'category',
          label: 'Local-First & Inference',
          items: [
            '04-tooling-and-frameworks/03-local-inference',
            {type: 'autogenerated', dirName: '04-tooling-and-frameworks/03-local-first'},
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '05 · Responsible AI',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '05-responsible-ai'}],
    },
    {
      type: 'category',
      label: 'Foundations (Reference)',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'foundations/01-generative-ai-introduction/introduction',
      },
      items: [
        {
          type: 'category',
          label: '01 · Generative AI Basics',
          items: [{type: 'autogenerated', dirName: 'foundations/01-generative-ai-introduction'}],
        },
        {
          type: 'category',
          label: '02 · LLM Deep Dive',
          items: [{type: 'autogenerated', dirName: 'foundations/02-llm-deep-dive'}],
        },
        {
          type: 'category',
          label: '03 · NLP Core Concepts',
          items: [{type: 'autogenerated', dirName: 'foundations/03-nlp-basics'}],
        },
        {
          type: 'category',
          label: '04 · Sequential Models',
          items: [{type: 'autogenerated', dirName: 'foundations/04-sequential-models'}],
        },
        {
          type: 'category',
          label: '05 · Attention & Transformers',
          items: [{type: 'autogenerated', dirName: 'foundations/05-attention-and-transformers'}],
        },
      ],
    },
    {
      type: 'category',
      label: '06 · Templates',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '06-templates'}],
    },
    {
      type: 'category',
      label: '07 · Experiments',
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'experiments/00-index',
          label: 'Overview',
        },
      ],
    },
    {
      type: 'category',
      label: '08 · Code & Snippets',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '08-code-and-snippets'}],
    },
    {
      type: 'doc',
      id: 'AGENTS',
      label: 'CLI Agents (General)',
    },
    {
      type: 'doc',
      id: 'CHANGELOG',
      label: 'Changelog',
    },
    {
      type: 'doc',
      id: 'LICENSE',
      label: 'License',
    },
  ],
};

module.exports = sidebars;
