/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    {
      type: 'category',
      label: '00 Standard',
      collapsed: false,
      items: [
        '00-start-here/00-what-is-nnlp',
        '00-start-here/06-scope-and-applicability',
        '00-start-here/07-prerequisites-and-entry-criteria',
        '03-nnlp-method/10-accountability-and-delegation',
        '03-nnlp-method/11-nnlp-loop-spec',
        '03-nnlp-method/12-artifact-contracts',
        '00-start-here/08-standard-core',
      ],
    },
    {
      type: 'category',
      label: '01 Method',
      collapsed: false,
      items: [
        '03-nnlp-method/00-the-nnlp-loop',
        '03-nnlp-method/01-discovery-brief',
        '03-nnlp-method/02-intent-spec',
        '03-nnlp-method/03-constraint-spec',
        '03-nnlp-method/04-delegation-contract',
        '03-nnlp-method/05-generation-requests',
        '03-nnlp-method/06-review-and-interrogation',
        '03-nnlp-method/07-acceptance-criteria',
        '03-nnlp-method/08-iteration-and-release',
        '03-nnlp-method/09-working-agreements-for-teams',
      ],
    },
    {
      type: 'category',
      label: '02 Skills & Fundamentals',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: '01-core-skills'},
        {type: 'autogenerated', dirName: '02-genai-llm-fundamentals'},
      ],
    },
    {
      type: 'category',
      label: '03 Playbooks',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: '04-execution-patterns'},
        {type: 'autogenerated', dirName: '05-professional-scenarios'},
      ],
    },
    {
      type: 'category',
      label: '04 Guardrails & Evaluation',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: '07-guardrails-and-governance'},
        {type: 'autogenerated', dirName: '08-evaluation'},
      ],
    },
    {
      type: 'category',
      label: '05 Tooling',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '06-frameworks-and-tooling'}],
    },
    {
      type: 'category',
      label: '06 Templates & Reference',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '09-templates'}],
    },
    {type: 'autogenerated', dirName: 'experiments'},
  ],
};

module.exports = sidebars;
